version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.15.4
    steps:
      - checkout
      - run: echo "NPM Installing"
      - run: yarn
      - run: CI=true yarn run build
  test:
    docker:
      - image: circleci/node:14.15.4
    steps:
      - checkout
      - run: echo "Running TESTS"
      - run: yarn
      - run: yarn test
  coverage:
    docker:
      - image: circleci/node:14.15.4
    steps:
      - checkout
      - run: echo "Running TESTS"
      - run: yarn
      - run: yarn test --coverage
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - coverage:
          requires:
            - build
            - test
